name: quiz_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0' # Atau sesuaikan dengan versi SDK Anda

dependencies:
  flutter:
    sdk: flutter

  # Dependencies lainnya
  # ...

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16

flutter:
  uses-material-design: true

  assets: